### PR TITLE
Downgrade Cypress

### LINKED ISSUE #56: cypress@8.5.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1"
## What
Node CI Environment error

## Why
Current version of Node seems to be incompatible after introducing Cypress to this repo.

```bash
Run yarn
  yarn
  yarn lint:dir src/
  shell: /usr/bin/bash -e {0}
yarn install v1.22.15
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error cypress@8.5.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

Reference: https://github.com/benji011/portfolio.benjaminlo.io/pull/54#issuecomment-939327410

### PR DESCRIPTION
**Pull request by sano2019**
## Description

Deleted the Cypress folder and downgraded the Cypress version to 5.0.0 in the package.json. This should allow this to work with with Node10.

Fixes #56 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I suppose this will be tested E2E as mentioned in the issue

- [ ] Manual
- [X] E2E

## Checklist:

- [X] My code follows the style guidelines of this project (confirmed with `yarn lint:dir <dir>`)
- [X] My code was automatically formatted to fit the style guidelines using `yarn lint:fix <dir>`
- [X] I have performed a self-review of my own code
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
- [?] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by benji011** [comment]
Hi @sano2019 , thanks for doing this! It looks like the CI passed so well done for getting this sorted.
One thing I noticed were a few deleted files in 3049d51a4d38c0c19ea545f86c6c4f62019d2b1e , Will reverting those changes back after the latest work for the install?

**Comment by sano2019** [comment]
@benji011 I haven't been able to check this really. I figured this cypress folder should be deleted because of an older version of cypress being installed. However, I suppose this folder held the actual tests and config for cypress.... I think a revert should work, assuming there are no breaking changes to the cypress files since 5.0.0. If there is a way I can test this, please do let me know, I wouldn't mind it.

**Comment by benji011** [comment]
Let's revert 3049d51a4d38c0c19ea545f86c6c4f62019d2b1e and push it then wait for the CI to run. Normally I just run the tests locally and if they pass even with an older version then should be fine. If the CI passes too then it's safe (this repo is quite small anyway so i'm fine with that approach)

**Comment by sano2019** [comment]
@benji011 Couldn't really see a way on github to revert, so I did it locally and reset to the downgrade of cypress. The files should be added again now. Let me know if there are any problems.

**Comment by benji011** [comment]
@sano2019 Just run the following to revert:

```bash
git revert a82a8d0a803cdbec7edbde2e871d14f0e171916c
```

Then it will create a new commit which you can push to these changes as a new change. After that all the deleted files will be added back from the commit history :)

**Comment by sano2019** [comment]
That should do it then @benji011 thanks for the help with that =) Kinda makes me feel like you still ended up doing most the work xD

**Review by benji011 — APPROVED** [review]
@sano2019 Nah that ain't true, it was a collaborative effort and I hope you had fun & learned stuff (which makes me happy too)

Since the CI passed I'm happy with these changes. Thanks again!

**Comment by sano2019** [comment]
I did learn some stuff for sure, thanks a lot for the opportunity! :) Hope it all works :)

**Pull request merged**
