### PR TITLE
I18n added provider

### PR DESCRIPTION
**Pull request by martink-rsa**
I've made the following changes:

1. Added the i18n dependencies back.
2. Uncommented the code in the i18n config file
3. Added a provider in index.js as well as the HOC that i18n provides.

image

Notes:

* It doesn't translate yet. You can see that the config file is part of the i18n data store, but the top-level language is `['en', 'dev']` instead of 'en' and 'ja'. I'm unsure of how to implement the translation at this stage as the config used differs to the documentation. It appears that this project uses a modular approach whereas the docs are a more basic implementation.
* The HOC and Provider could be moved to `gatsby-browser.js` then it will affect all of your pages included the 404.

### CODE REVIEW

**Comment by benji011** [comment]
@martink-rsa Hi, I had a look at the changes locally but I still was not able to build. Please see log below for details:

<details>
  <summary>Build log</summary>

```bash
❯ yarn && yarn build
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.92s.
yarn run v1.22.10
$ gatsby build
success open and validate gatsby-configs - 0.076s
success load plugins - 0.880s
success onPreInit - 0.020s
success delete html and css files from previous builds - 0.059s
success initialize cache - 0.010s
success copy gatsby files - 0.079s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.007s
success source and transform nodes - 1.341s
success building schema - 0.486s
success createPages - 0.022s
success createPagesStatefully - 0.107s
success onPreExtractQueries - 0.003s
success update schema - 0.043s
success extract queries from components - 0.428s
success write out requires - 0.013s
success write out redirect data - 0.004s
warn The icon(./static/favicon/favicon-512.png) you provided to 'gatsby-plugin-manifest' is not square.
The icons we generate will be square and for the best results we recommend you provide a square icon.

success Build manifest and related icons - 0.154s
success onPostBootstrap - 0.169s
⠀
info bootstrap finished - 6.512 s
⠀
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
success Building production JavaScript and CSS bundles - 12.131s
success run queries - 13.384s - 6/6 0.45/s
failed Building static HTML for pages - 3.467s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html



  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev e  nvironment for full errors and additional helpful warnings.

  - react-dom-server.node.production.min.js:44 a.b.read
    [gatsby-portfolio-dev]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:107

  - react-dom-server.node.production.min.js:54 renderToString
    [gatsby-portfolio-dev]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:611 Module../.cache/static-entry.js.__webpack_exports__.default
    /Users/benji0110/Documents/personal_projects/github/gatsby-portfolio-dev/public/render-page.js:611:28

  - render-html.js:28
    [gatsby-portfolio-dev]/[gatsby]/dist/utils/worker/render-html.js:28:36

  - debuggability.js:384 Promise._execute
    [gatsby-portfolio-dev]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [gatsby-portfolio-dev]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [gatsby-portfolio-dev]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:24
    [gatsby-portfolio-dev]/[gatsby]/dist/utils/worker/render-html.js:24:47

  - util.js:16 tryCatcher
    [gatsby-portfolio-dev]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [gatsby-portfolio-dev]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [gatsby-portfolio-dev]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [gatsby-portfolio-dev]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [gatsby-portfolio-dev]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [gatsby-portfolio-dev]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [gatsby-portfolio-dev]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [gatsby-portfolio-dev]/[bluebird]/js/release/async.js:102:5


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

Running locally works fine though. Can I confirm this is the same for you as well?

**Comment by martink-rsa** [comment]
My apologies, the build is also failing for me. Having a look at why this is.

**Comment by TheGarious** [comment]
@benji011 @martink-rsa I looking this Pull Request, many line from Readme are deleting, it's normal ? 
 

data/landing/skills.json : 
- You have replace this variable {{ count }} by 7 why ? 

package.json : 
- Why remove replace "eslint . --fix" by "yarn prettier --write src/", eslint works.

**Comment by benji011** [comment]
@TheGarious Hi! 

> data/landing/skills.json : 
> 
> - You have replace this variable {{ count }} by 7 why ? 

This will be reverted back later. Because i18next is still a WIP I hardcoded this value temporarily. 

> package.json : 
> 
> - Why remove replace "eslint . --fix" by "yarn prettier --write src/", eslint works.
> 

It's just my personal preference 😅 although I am reconsidering my choices

**Comment by TheGarious** [comment]
@benji011 Hi, i didn't see who have got this commit, my bad.. 
I thought that not you for this commit. Not problem then 👍

**Comment by martink-rsa** [comment]
I think I've managed to pinpoint the two issues you were originally having.

## 1. React suspense:

  i18n appears to use Suspense but this is problematic for Gatsby. See [here](https://github.com/gatsbyjs/gatsby/issues/20371). 

The fix is quite straightforward and I've added it to the config.

## 2. The `i18ncheck` statement:
```const i18nCheck = i18n.languages.toLowerCase().includes('en') || i18n.languages.toLowerCase().includes('en-');```

This statement is problematic.

There are two variables. `language`, which I think is the current language, and is set to a string: `en`

There is another variable, `languages` which is an array of languages. This is set to `['en', 'dev']`.

If you want to check for the array `languages`, then we can't use `toLowerCase()` like it was used. It will result in an error. We would have to loop through the array and then apply `toLowerCase()`. I don't think you were wanting to check the array though as the language, for example 'en', would always be in the array.

Another issue related to this is that `i18n` might not have the property yet, so we need to check that it has the property first.

## Regarding ESLint and Prettier:

You should use both. 

ESLint is a linter and will show code errors. The project already has an ESLint config, you just need the plugin. There might be a window that pops up when you open the project, which you must then choose `Allow`.

Prettier is a formatter and will format your code e.g. add a semi-colon at the end of lines.

**Review by benji011 — APPROVED** [review]
@martink-rsa Thank you so much!! Build works on my end 🚀 
LGTM :)

**Pull request merged**
